name: Update API
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * 1-12 6'

  workflow_dispatch:
jobs:
  build:   
    runs-on: ubuntu-latest   
    steps:      
      - uses: actions/checkout@v3
      - name: Installing Requirements
        run: |
          pip3 install -r requirements.txt
      - name: Run Website Compiler Job
        run: |
          python3 compilerjob.py
      - name: Publish Website
        if: success() || failure()
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Compiled/Updated TotalEnergiesWiCode"
          git push
